### ISSUE TITLE
build errors 

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Ares#218]
$ npm run build

> ares@0.1.0 build
> vite build --out-dir dist

vite v4.1.1 building for production...
transforming (198) node_modules\vuetify\lib\components\VExpansionPanel\VExpansionPanelText.mjsfile:///D:/OHDSI/Ares/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22004
    throw new Error(`Failed to resolve entry for package "${id}". ` +
          ^

Error: Failed to resolve entry for package "vuetify". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///D:/OHDSI/Ares/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22004:11)
    at resolvePackageEntry (file:///D:/OHDSI/Ares/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22001:5)
    at tryNodeResolve (file:///D:/OHDSI/Ares/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21736:20)
    at Context.resolveId (file:///D:/OHDSI/Ares/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21487:28)
    at Object.resolveId (file:///D:/OHDSI/Ares/node_modules/vite/dist/node/chunks/dep-3007b26d.js:41587:46)
    at async Object.<anonymous> (file:///D:/OHDSI/Ares/node_modules/vite/dist/node/chunks/dep-3007b26d.js:61953:21)

**Comment by Mikhail-iontsev** [comment]
I haven't encountered any errors during building.

What version of node are you using? 

Please also consider deleting node_modules folder and package-lock.json before running npm install to prevent any incompatibilities.

**Comment by Mikhail-iontsev** [comment]
I got the error after reinstalling node_modules. Looking into it.

**Comment by Mikhail-iontsev** [comment]
https://github.com/vuetifyjs/vuetify/issues/16593

The issue is due to vite 4.1.0 update. Will lock 4.0.4 version until a solution is released.
